repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # please config the same version as in requirements.txt
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==24.2.10',
            'flake8-comprehensions==3.14.0',
            'pep8-naming==0.14.0'
        ]
        args: [
            '--max-line-length=79',
            '--select=E1,E2,E3,E9,N,W',
            '--exclude=.git,__pycache__,build,dist,venv,app/static,app/templates'
        ] 