from enum import Enum

class AuditActionType(Enum):
    # User Management Actions:
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_SESSION_TIMEOUT = "USER_SESSION_TIMEOUT"
    USER_REGISTER = "USER_REGISTER"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    USER_PASSWORD_RESET = "USER_PASSWORD_RESET"
    USER_PASSWORD_CHANGE = "USER_PASSWORD_CHANGE"
    USER_ACCOUNT_BAN = "USER_ACCOUNT_BAN"
    USER_ACCOUNT_UNBAN = "USER_ACCOUNT_UNBAN"
    USER_ROLE_UPDATE = "USER_ROLE_UPDATE"

    # Content Actions:
    CONTENT_CREATE = "CONTENT_CREATE"
    CONTENT_READ = "CONTENT_READ"
    CONTENT_UPDATE = "CONTENT_UPDATE"
    CONTENT_DELETE = "CONTENT_DELETE"
    CONTENT_APPROVE = "CONTENT_APPROVE"
    CONTENT_REJECT = "CONTENT_REJECT"
    CONTENT_SHARE = "CONTENT_SHARE"
    CONTENT_ARCHIVE = "CONTENT_ARCHIVE"

    # System Actions:
    SYSTEM_START = "SYSTEM_START"
    SYSTEM_STOP = "SYSTEM_STOP"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SYSTEM_WARNING = "SYSTEM_WARNING"
    SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE"
    SYSTEM_UPDATE = "SYSTEM_UPDATE"
    SYSTEM_BACKUP = "SYSTEM_BACKUP"
    SYSTEM_RESTORE = "SYSTEM_RESTORE"

    # Transaction Actions:
    TRANSACTION_INITIATE = "TRANSACTION_INITIATE"
    TRANSACTION_COMPLETE = "TRANSACTION_COMPLETE"
    TRANSACTION_CANCEL = "TRANSACTION_CANCEL"

    # Tutorys
    TUTORY_ADQUIRED = "TUTORY_ADQUIRED"

    # Miscellaneous/Other Actions:
    # ...
