############################

# FIREBASEACCOUNTKEY.JSON MUST BE ADDED TO THE REPOSITORY SECRETS WITH ADMIN PRIVILEGES

############################


#name: Run Pytest

#on:
#  push:
#    branches: [ main, feature/allow-change-password ]
#  pull_request:
#    branches: [ main ]

#jobs:
#  testing:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checking out repository
#        uses: actions/checkout@v3

#      - name: Setting up Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.13.2'

#       #THE SECRE HAS TO BE ADDED TO THE REPOSITORY BEFOREHAND. ADMIN PRIVILEGES REQUIERED
#      - name: Creating Firebase key file
#        run: echo "${{ secrets.FIREBASE_KEY }}" > firebaseAccountKey.json

#      - name: Installing dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

#      - name: Running tests with Pytest
#        run: |
#          pytest tests
